[
  {
    "d0:cf:13:c:9e:c0": 1,
    "dimmerSet": 20,
    "onlyBins": true,
    "bright": 100,
    "askSpiffs": true,
    "wui_usr": "admin",
    "wui_pwd": "launcher",
    "dwn_path": "/downloads/",
    "FGCOLOR": 2016,
    "BGCOLOR": 0,
    "ALCOLOR": 63488,
    "even": 13029,
    "odd": 12485,
    "favorite": [],
    "wifi": [
      {
        "ssid": "myNetSSID",
        "pwd": "myNetPassword"
      }
    ],
    "dev": false,
    "d8:85:ac:a5:a2:38": 1
  }
]